// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/storage.proto

package storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataEntry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataEntry) Reset()         { *m = DataEntry{} }
func (m *DataEntry) String() string { return proto.CompactTextString(m) }
func (*DataEntry) ProtoMessage()    {}
func (*DataEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_18a822e70024d46b, []int{0}
}

func (m *DataEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataEntry.Unmarshal(m, b)
}
func (m *DataEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataEntry.Marshal(b, m, deterministic)
}
func (m *DataEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataEntry.Merge(m, src)
}
func (m *DataEntry) XXX_Size() int {
	return xxx_messageInfo_DataEntry.Size(m)
}
func (m *DataEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DataEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DataEntry proto.InternalMessageInfo

func (m *DataEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DataEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*DataEntry)(nil), "storage.DataEntry")
}

func init() {
	proto.RegisterFile("services/storage.proto", fileDescriptor_18a822e70024d46b)
}

var fileDescriptor_18a822e70024d46b = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x8c, 0xb9, 0x38, 0x5d, 0x12, 0x4b, 0x12, 0x5d, 0xf3,
	0x4a, 0x8a, 0x2a, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26, 0xb0, 0x18,
	0x84, 0x63, 0xe4, 0xc3, 0x25, 0x04, 0xd2, 0x14, 0x0c, 0x31, 0x23, 0x18, 0x62, 0x85, 0x90, 0x19,
	0x17, 0x97, 0x67, 0x5e, 0x41, 0x69, 0x09, 0xc4, 0x2c, 0x21, 0x3d, 0x98, 0x8d, 0x70, 0xf3, 0xa5,
	0xb0, 0x88, 0x29, 0x31, 0x24, 0xb1, 0x81, 0x9d, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x23,
	0x3f, 0x6f, 0x4b, 0xac, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataStorageServiceClient is the client API for DataStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataStorageServiceClient interface {
	InputEntry(ctx context.Context, in *DataEntry, opts ...grpc.CallOption) (*DataEntry, error)
}

type dataStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataStorageServiceClient(cc grpc.ClientConnInterface) DataStorageServiceClient {
	return &dataStorageServiceClient{cc}
}

func (c *dataStorageServiceClient) InputEntry(ctx context.Context, in *DataEntry, opts ...grpc.CallOption) (*DataEntry, error) {
	out := new(DataEntry)
	err := c.cc.Invoke(ctx, "/storage.DataStorageService/InputEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataStorageServiceServer is the server API for DataStorageService service.
type DataStorageServiceServer interface {
	InputEntry(context.Context, *DataEntry) (*DataEntry, error)
}

// UnimplementedDataStorageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataStorageServiceServer struct {
}

func (*UnimplementedDataStorageServiceServer) InputEntry(ctx context.Context, req *DataEntry) (*DataEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InputEntry not implemented")
}

func RegisterDataStorageServiceServer(s *grpc.Server, srv DataStorageServiceServer) {
	s.RegisterService(&_DataStorageService_serviceDesc, srv)
}

func _DataStorageService_InputEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStorageServiceServer).InputEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.DataStorageService/InputEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStorageServiceServer).InputEntry(ctx, req.(*DataEntry))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataStorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.DataStorageService",
	HandlerType: (*DataStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InputEntry",
			Handler:    _DataStorageService_InputEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/storage.proto",
}
